---
- hosts: test
  gather_facts: yes
  remote_user: root

  tasks:
    - name: Execute CentOS 6 tasks
      include_role:
        name: nginx/centos6_nginx
      when: "'CentOS' in ansible_distribution and ansible_distribution_major_version == '6'"

    - name: Execute CentOS 7 tasks
      include_role:
        name: nginx/centos7_nginx
      when: "'CentOS' in ansible_distribution and ansible_distribution_major_version == '7'"

    - name: Execute CentOS 8 tasks
      include_role:
        name: nginx/centos8_nginx
      when: "'CentOS' in ansible_distribution and ansible_distribution_major_version == '8'"
