---
- hosts: test
  gather_facts: yes
  remote_user: root

  tasks:
    - name: Execute CentOS 6 tasks
      include_role:
        name: php/centos6_php
      when: "'CentOS' in ansible_distribution and ansible_distribution_major_version == '6'"

    - name: Execute CentOS 7 tasks
      include_role:
        name: php/centos7_php
      when: "'CentOS' in ansible_distribution and ansible_distribution_major_version == '7'"

    - name: Execute CentOS 8 tasks
      include_role:
        name: php/centos8_php
      when: "'CentOS' in ansible_distribution and ansible_distribution_major_version == '8'"
