- name: Create backup directory
  ansible.builtin.file:
    path: /usr/local/src/yum_backup
    state: directory

- name: Move .repo files to backup directory
  ansible.builtin.shell:
    cmd: "mv /etc/yum.repos.d/* /usr/local/src/yum_backup/"

- name: Wget CentOS-Base.repo files
  ansible.builtin.get_url:
    url: https://mirrors.aliyun.com/repo/Centos-vault-8.5.2111.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo
    backup: yes
  become: yes

- name: Clean up the yum cache
  ansible.builtin.shell:
    cmd: yum clean all && yum makecache
  become: yes

- name: Create a www group
  group:
    name: www
    state: present

- name: Create a www user
  user:
    name: www
    group: www
    shell: /sbin/nologin
    create_home: no
    system: yes

- name: Install the required packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - gcc
    - tcl
    - gcc-c++
    - sqlite
    - sqlite-devel
    - oniguruma
    - cmake3
    - openssl-devel
    - libxml2
    - libxml2-devel
    - libcurl-devel
    - libpng-devel
    - libjpeg
    - libjpeg-devel
    - freetype-devel
    - libxslt-devel
    - autoconf
    - libzstd
    - libxslt 
    - libtool-ltdl-devel.x86_64

- name: Copy installation package to remote host
  copy:
    src: "files/{{ item }}"
    dest: "/usr/local/src/{{ item }}"
  with_items:
    - php-7.4.20.tar.gz
    - onig-6.9.5-rev1.tar.gz

- name: Unzip installation package
  unarchive:
    src: /usr/local/src/{{ item }} 
    dest: /usr/local/src/
    remote_src: yes 
  with_items:
    - php-7.4.20.tar.gz
    - onig-6.9.5-rev1.tar.gz
