- name: 设置yum源
  ansible.builtin.shell:
    cmd: |
      mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup &&
      mv /etc/yum.repos.d/epel.repo /etc/yum.repos.d/epel.repo.backup &&
      wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.cloud.tencent.com/repo/centos6_base.repo &&
      wget -O /etc/yum.repos.d/epel.repo http://mirrors.cloud.tencent.com/repo/epel-6.repo &&
      yum clean all &&
      yum makecache
  become: yes

- name: Create mysql group
  group:
    name: mysql
    state: present

- name: Create mysql user
  user:
    name: mysql
    group: mysql
    create_home: false
    shell: /sbin/nologin
    system: yes

- name: Install Packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - cmake
    - ncurses-devel
    - openssl-devel
    - bison
    - bison-devel
    - gcc
    - gcc-c++
    - autoconf
    - libselinux-python

- name: Download MySQL tarball
  get_url:
    url: http://mirrors.aliyun.com/mysql/MySQL-5.6/mysql-5.6.50.tar.gz
    dest: /usr/local/src/mysql-5.6.50.tar.gz 
    mode: 0644

- name: Extract MySQL tarball
  ansible.builtin.unarchive:
    src: /usr/local/src/mysql-5.6.50.tar.gz
    dest: /usr/local/src
    remote_src: yes
